import { useState } from 'react';
import Head from 'next/head';

const T = {
  en: { title:'DayFlow AI', tagline:'Describe your day. Get a smart plan.', inputLabel:'What does your day look like?', placeholder:`Tell me about your day in plain language. For example:\n\n"I have a meeting downtown at 10am that usually lasts an hour. Need to finish a report for my boss, probably 2 hours of work. Gym session in the afternoon, 45 minutes. Pick up kids at 5:30pm."`, btn:'Generate my plan  ✶', loading:'Planning your day...', yourPlan:'Your schedule', tips:'Tips for today', newPlan:'← New plan', footer:'Made with', freeBadge:'3 plans / day free', errorTitle:'Something went wrong', langBtn:'ES' },
    es: { title:'DayFlow AI', tagline:'Describ\u00ed tu d\u00eda. Obten\u00e9 un plan inteligente.', inputLabel:'\u00bfC\u00f3mo es tu d\u00eda?', placeholder:`Cont\u00e1me sobre tu d\u00eda en lenguaje natural. Por ejemplo:\n\n"Tengo una reuni\u00f3n en el centro a las 10am que dura aproximadamente una hora. Necesito terminar un informe para mi jefe, calculo 2 horas. Gimnasio por la tarde, 45 minutos. Buscar a los chicos a las 17:30."`, btn:'Generar mi plan  ✶', loading:'Planificando tu d\u00eda...', yourPlan:'Tu horario', tips:'Consejos para hoy', newPlan:'← Nuevo plan', footer:'Hecho con', freeBadge:'3 planes / d\u00eda gratis', errorTitle:'Algo sali\u00f3 mal', langBtn:'EN' }
    };
h
    export default function Home() {
      const [lang, setLang] = useState('en');
        const [description, setDescription] = useState('');
          const [plan, setPlan] = useState(null);
            const [loading, setLoading] = useState(false);
              const [error, setError] = useState(null);
                const t = T[lang];

                  async function handleGenerate() {
                      if (!description.trim()) return;
                          setLoading(true); setError(null); setPlan(null);
                              try {
                                    const res = await fetch('/api/plan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ description, lang }) });
                                          const data = await res.json();
                                                if (!res.ok) throw new Error(data.error || 'Unknown error');
                                                      setPlan(data);
                                                          } catch (e) { setError(e.message); }
                                                              finally { setLoading(false); }
                                                                }

                                                                  return (
                                                                      <>
                                                                            <Head><title>DayFlow AI</title><meta name="viewport" content="width=device-width, initial-scale=1" /></Head>
                                                                                  <div style={{minHeight:'100vh',backgroundColor:'var(--bg)',display:'flex',alignItems:'flex-start',justifyContent:'center',padding:'2rem 1rem 4rem'}}>
                                                                                          <div style={{width:'100%',maxWidth:'620px'}}>
                                                                                                    <header style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:'2.5rem'}}>
                                                                                                                <div>
                                                                                                                              <h1 style={{fontFamily:"'Instrument Serif',serif",fontSize:'32px',fontWeight:400,color:'var(--text-primary)',letterSpacing:'-0.5px',lineHeight:1}}>Day<span style={{color:'var(--coral)'}}>Flow</span></h1>
                                                                                                                                            <p style={{fontSize:'14px',color:'var(--text-secondary)',marginTop:'6px'}}>{t.tagline}</p>
                                                                                                                                                        </div>
                                                                                                                                                                    <button onClick={()=>setLang(lang==='en'?'es':'en')} style={{fontSize:'13px',padding:'5px 14px',borderRadius:'20px',cursor:'pointer',background:'transparent',border:'0.5px solid var(--border-strong)',color:'var(--text-secondary)',marginTop:'4px'}}>{t.langBtn}</button>
                                                                                                                                                                              </header>
                                                                                                                                                                              
                                                                                                                                                                                        {!plan && (
                                                                                                                                                                                                    <main>
                                                                                                                                                                                                                  <label style={{display:'block',fontSize:'13px',fontWeight:500,color:'var(--text-secondary)',textTransform:'uppercase',letterSpacing:'0.07em',marginBottom:'10px'}}>{t.inputLabel}</label>
                                                                                                                                                                                                                                <textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder={t.placeholder} rows={9} style={{width:'100%',padding:'14px 16px',fontSize:'14.5px',lineHeight:1.7,resize:'vertical',borderRadius:'var(--radius)',border:'0.5px solid var(--border)',background:'var(--bg-card)',color:'var(--text-primary)',outline:'none',minHeight:'200px',fontFamily:"'DM Sans',sans-serif"}} />
                                                                                                                                                                                                                                              {error && <div style={{marginTop:'1rem',padding:'12px 16px',background:'#FEF2F2',borderRadius:'var(--radius-sm)',border:'0.5px solid #FECACA'}}><p style={{fontSize:'13px',color:'#DC2626'}}><strong>{t.errorTitle}.</strong> {error}</p></div>}
                                                                                                                                                                                                                                                            <button onClick={handleGenerate} disabled={loading||!description.trim()} style={{display:'block',width:'100%',marginTop:'1rem',padding:'14px',fontSize:'15px',fontWeight:500,border:'none',borderRadius:'var(--radius)',background:'var(--coral)',color:'#fff',cursor:loading||!description.trim()?'not-allowed':'pointer',opacity:loading||!description.trim()?0.5:1,fontFamily:"'DM Sans',sans-serif"}}>{loading?t.loading:t.btn}</button>
                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                            {plan && (
                                                                                                                                                                                                                                                                                                        <main>
                                                                                                                                                                                                                                                                                                                      <button onClick={()=>{setPlan(null);setDescription('');}} style={{background:'transparent',border:'none',fontSize:'13px',color:'var(--text-secondary)',cursor:'pointer',marginBottom:'1.5rem'}}>{t.newPlan}</button>
                                                                                                                                                                                                                                                                                                                                    <div style={{padding:'14px 16px',background:'var(--info-bg)',borderRadius:'var(--radius)',marginBottom:'1.5rem'}}><p style={{fontSize:'14px',color:'var(--info-text)',lineHeight:1.65}}>{plan.summary}</p></div>
                                                                                                                                                                                                                                                                                                                                                  <p style={{fontSize:'11.5px',fontWeight:500,color:'var(--text-tertiary)',textTransform:'uppercase',letterSpacing:'0.07em',marginBottom:'0.75rem'}}>{t.yourPlan}</p>
                                                                                                                                                                                                                                                                                                                                                                <div style={{display:'flex',flexDirection:'column',gap:'8px'}}>
                                                                                                                                                                                                                                                                                                                                                                                {plan.schedule?.map((item,i)=>(
                                                                                                                                                                                                                                                                                                                                                                                                  <div key={i} style={{background:'var(--bg-secondary)',borderRadius:'var(--radius-sm)',padding:'12px 14px',borderLeft:'2.5px solid var(--coral)'}}>
                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{display:'flex',justifyContent:'space-between',alignItems:'baseline',gap:'8px',marginBottom:'4px',flexWrap:'wrap'}}>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <span style={{fontSize:'14px',fontWeight:500}}>{item.task}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span style={{fontSize:'12px',color:'var(--text-tertiary)'}}>{item.time}  ·  {item.duration}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {item.note&&<p style={{fontSize:'13px',color:'var(--text-secondary)',lineHeight:1.55}}>{item.note}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {plan.tips?.length>0&&<>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p style={{fontSize:'11.5px',fontWeight:500,color:'var(--text-tertiary)',textTransform:'uppercase',letterSpacing:'0.07em',margin:'1.5rem 0 0.75rem'}}>{t.tips}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {plan.tips.map((tip,i)=><div key={i} style={{display:'flex',gap:'10px',marginBottom:'8px',alignItems:'flex-start'}}><span style={{color:'var(--coral)',flexShrink:0}}>✶</span><span style={{fontSize:'13px',color:'var(--text-secondary)',lineHeight:1.6}}>{tip}</span></div>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <footer style={{marginTop:'3rem',paddingTop:'1rem',borderTop:'0.5px solid var(--border)',display:'flex',justifyContent:'space-between',alignItems:'center'}}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span style={{fontSize:'12px',color:'var(--text-tertiary)'}}>{t.footer} <span style={{fontFamily:"'Instrument Serif',serif",color:'var(--coral)'}}>DayFlow</span> AI</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span style={{fontSize:'12px',color:'var(--text-tertiary)'}}>{t.freeBadge}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
